### PR TITLE
All bugs fixed

### PR DESCRIPTION
**Pull request by wcyz666**
This is the final version of IEWAVE and cuhk link. I have tested them.

### CODE REVIEW

**Comment by wcyz666** [comment]
Happy Chinese New Year~

**Comment by TangRufus** [comment]
Chrome web store rejected.
>> The manifest defines an invalid url: *://192.168.110.1:*/www/login.chi?*.

v8.0.2 changes this to `*://192.168.110.1*/www/login.chi*`
Please check if it works.

Thanks!

**Comment by TangRufus** [comment]
Google chrome doesn't accept the wildcard port
v8.0.3 changes it to `*://192.168.110.1/www/login.chi*`

**Comment by wcyz666** [comment]
OK, I will check it after I come back to CUHK

**Comment by wcyz666** [comment]
Yes, it works well

**Pull request merged**
