### PR TITLE
Add IEWAVE auto login

### PR DESCRIPTION
**Pull request by wcyz666**
I have tested this function using my account and it works.

### CODE REVIEW

**Comment by TangRufus** [comment]
Looks great!
Please add `redirectAfterLogin()` after successful IEWave login.
Note that i have refactored some parts of `login.js`, merge it first

**Comment by wcyz666** [comment]
OK, I will do that

**Comment by wcyz666** [comment]
Done :smile:

**Comment by wcyz666** [comment]
Seems there are still some conflicts but I think it's due to Git itself....

**Comment by TangRufus** [comment]
`redirectAfterLogin()` should be called on a *successful page* not the login form.
You need to check for the successful message from IEWave on a separate if/else block, such as `You have logged in IEWave` (i don't know what is it exactly)

Sorry for the conflicts, I change some spaces to tabs. Ignore them.

**Comment by wcyz666** [comment]
Ok, I understand what you mean. I will give a final version tomorrow.

**Pull request closed without merging**
